# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: frameworkium-bdd build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  THREAD_COUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 1.8, 1.11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven - download dependencies and compile
        run: mvn test-compile -B --show-version -DskipTests=true -Dmaven.javadoc.skip=true
      - name: Build with Maven - firefox off grid
        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=firefox -DreuseBrowser -Dheadless -Dwebdriver.firefox.logfile=/dev/null
      - name: Build with Maven - chrome on grid
        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=chrome -Dmaximise=True -DreuseBrowser=true -Dheadless=true -DgridURL=http://localhost:4444/wd/hub
        # Disabled until we have a JIRA to use
        #      - name: Build with Maven
        #        run: mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=chrome -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium
      - name: Build allure report
        if: always()
        run: mvn allure:report -B




